# Generated by Django 4.2 on 2024-05-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery_Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('logo', models.ImageField(upload_to='logo')),
                ('subtitle', models.TextField(max_length=2000)),
                ('call_us', models.CharField(blank=True, max_length=120, null=True)),
                ('email_us', models.CharField(blank=True, max_length=120, null=True)),
                ('phones', models.TextField(blank=True, max_length=120, null=True)),
                ('android_apps', models.URLField(blank=True, null=True)),
                ('ios_app', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('address', models.TextField(max_length=500)),
            ],
        ),
    ]
