# Generated by Django 4.2 on 2024-05-28 09:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copoun',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
